# AeroSpace window manager installation
# Documentation: https://nikitabobko.github.io/AeroSpace/

[tools]
# AeroSpace - i3-like tiling window manager for macOS
"brew:nikitabobko/tap/aerospace" = "latest"

[tasks.start-aerospace]
description = "Start AeroSpace window manager"
run = "aerospace"

[tasks.reload-aerospace]
description = "Reload AeroSpace configuration"
run = [
    "aerospace reload-config",
    "echo 'AeroSpace configuration reloaded'",
]

[tasks.verify-aerospace]
description = "Verify AeroSpace installation and show version"
run = [
    "aerospace --version",
    "echo 'AeroSpace config location: ~/.config/aerospace/aerospace.toml'",
]

[tasks.list-workspaces]
description = "List all AeroSpace workspaces"
run = "aerospace list-workspaces --all"

[tasks.aerospace-help]
description = "Show AeroSpace help"
run = "aerospace --help"
