# TMUX terminal multiplexer installation
# Documentation: https://github.com/tmux/tmux

[tools]
# TMUX - Terminal multiplexer
"brew:tmux" = "latest"

[tasks.setup-tmux]
description = "Install TMUX Plugin Manager"
run = [
    "git clone https://github.com/tmux-plugins/tpm ~/.config/tmux/plugins/tpm || echo 'TPM already installed'",
    "echo 'TPM installed. Press prefix + I in tmux to install plugins.'",
]

[tasks.verify-tmux]
description = "Verify TMUX installation and show version"
run = [
    "tmux -V",
    "echo 'TMUX config location: ~/.config/tmux/tmux.conf'",
]

[tasks.reload-tmux]
description = "Reload TMUX configuration"
run = "tmux source-file ~/.config/tmux/tmux.conf || echo 'Start tmux first, then reload with prefix + R'"
