# WezTerm terminal emulator installation
# Documentation: https://wezfurlong.org/wezterm/

[tools]
# WezTerm - GPU-accelerated terminal emulator
"brew:wezterm" = { type = "cask" }

[tasks.verify-wezterm]
description = "Verify WezTerm installation and list available fonts"
run = [
    "wezterm --version",
    "echo 'Listing system fonts...'",
    "wezterm ls-fonts --list-system | grep -i jetbrains",
]

[tasks.open-wezterm]
description = "Open WezTerm terminal"
run = "open -a WezTerm"
